version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend-dev
    networks:
      - app-network-dev

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb-dev:27017/controlacceso
      - JWT_SECRET=development-secret-key
      - REDIS_URL=redis://redis-dev:6379
    depends_on:
      - mongodb-dev
      - redis-dev
    networks:
      - app-network-dev

  mongodb-dev:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - app-network-dev

  redis-dev:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
  redis_data_dev:
